### ISSUE TITLE
Error on populate

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/kegg#11]
I just did a totally clean installation with ``bio2bel_kegg populate`` and got the following error (some number of hours later...). It looks like it's not handling situations when multiple UniProt identifiers are listed.

```python-traceback
Loading pathways: 100%|███████████████████████████████████████████████████████████████████████████████| 330/330 [00:00<00:00, 1082.08it/s]
Fetching meta information: 7528it [1:35:51,  1.31it/s]
Loading proteins: 100%|███████████████████████████████████████████████████████████████████████████| 30036/30036 [00:29<00:00, 1027.97it/s]
Traceback (most recent call last):
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: value too long for type character varying(255)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/manager/abstract_manager.py", line 38, in populate_wrapped
    cls._populate_original(self, *populate_args, **populate_kwargs)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/bio2bel_kegg/manager.py", line 215, in populate
    self._pathway_entity(url=protein_pathway_url, metadata_existing=metadata_existing)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/bio2bel_kegg/manager.py", line 172, in _pathway_entity
    self.session.commit()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 866, in _emit_insert_statements
    execute(statement, params)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(255)
 [SQL: 'INSERT INTO kegg_protein (kegg_id, uniprot_id, hgnc_id, hgnc_symbol) VALUES (%(kegg_id)s, %(uniprot_id)s, %(hgnc_id)s, %(hgnc_symbol)s) RETURNING kegg_protein.id'] [parameters: {'kegg_id': 'hsa:3111', 'uniprot_id': 'P06340 X5CF87 A0A1V0E3P9 A0A1V0E3R6 A0A1V0E3Q3 A0A1V0E3Q1 A0A1V0E3N6 A0A1V0E3Q5 A0A1V0E3S4 A0A1V0E3P3 A0A1V0E3N7 A0A1V0E3R0 A0A1V0E3Q4 A0A1V0E3R4 A0A ... (34 characters truncated) ... V0E3R3 A0A1V0E3S6 A0A1V0E3P1 A0A1V0E3M7 A0A1V0E3P0 A0A1V0E3S0 A0A1V0E3T1 A0A1V0E3P6 A0A1V0E3Q2 A0A1V0E3Q8 A0A1V0E3R8 A0A1V0E3S7 A0A1V0E3N3 A0A1V0E3Q6', 'hgnc_id': '4936', 'hgnc_symbol': 'HLA-DOA'}] (Background on this error at: http://sqlalche.me/e/9h9h)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cthoyt/.virtualenvs/pybel/bin/bio2bel", line 11, in <module>
    load_entry_point('bio2bel', 'console_scripts', 'bio2bel')()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/cli.py", line 162, in write
    r = manager.write_directory(directory)
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/manager/namespace_manager.py", line 384, in write_directory
    self.write_bel_namespace(file, use_names=False)
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/manager/namespace_manager.py", line 346, in write_bel_namespace
    self.populate()
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/manager/abstract_manager.py", line 40, in populate_wrapped
    self._store_populate_failed()
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/manager/connection_manager.py", line 93, in _store_populate_failed
    Action.store_populate_failed(self.module_name, session=self.session)
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/models.py", line 95, in store_populate_failed
    _store_helper(action, session=session)
  File "/Users/cthoyt/dev/bio2bel/src/bio2bel/models.py", line 140, in _store_helper
    session.commit()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 465, in commit
    self._assert_active(prepared_ok=True)
  File "/Users/cthoyt/.virtualenvs/pybel/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.DataError) value too long for type character varying(255)
 [SQL: 'INSERT INTO kegg_protein (kegg_id, uniprot_id, hgnc_id, hgnc_symbol) VALUES (%(kegg_id)s, %(uniprot_id)s, %(hgnc_id)s, %(hgnc_symbol)s) RETURNING kegg_protein.id'] [parameters: {'kegg_id': 'hsa:3111', 'uniprot_id': 'P06340 X5CF87 A0A1V0E3P9 A0A1V0E3R6 A0A1V0E3Q3 A0A1V0E3Q1 A0A1V0E3N6 A0A1V0E3Q5 A0A1V0E3S4 A0A1V0E3P3 A0A1V0E3N7 A0A1V0E3R0 A0A1V0E3Q4 A0A1V0E3R4 A0A ... (34 characters truncated) ... V0E3R3 A0A1V0E3S6 A0A1V0E3P1 A0A1V0E3M7 A0A1V0E3P0 A0A1V0E3S0 A0A1V0E3T1 A0A1V0E3P6 A0A1V0E3Q2 A0A1V0E3Q8 A0A1V0E3R8 A0A1V0E3S7 A0A1V0E3N3 A0A1V0E3Q6', 'hgnc_id': '4936', 'hgnc_symbol': 'HLA-DOA'}] (Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by ddomingof** [comment]
Fixed. Thanks!!
