### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.api'

### ISSUE THREAD

**Issue by kozo2** [bio2bel/kegg#17]
I got an error like

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel_kegg\__init__.py", line 19, in <module>
    from .manager import Manager  # noqa: F401
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel_kegg\manager.py", line 10, in <module>
    from bio2bel.compath import CompathManager
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel\__init__.py", line 45, in <module>
    from .manager import AbstractManager, get_bio2bel_manager_classes  # noqa: F401
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel\manager\__init__.py", line 5, in <module>
    from .abstract_manager import AbstractManager, get_bio2bel_manager_classes
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel\manager\abstract_manager.py", line 14, in <module>
    from sqlalchemy.ext.declarative.api import DeclarativeMeta
ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.api'
```

when I did 

```
(base) C:\Users\hoge>python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bio2bel_kegg
```

Please let me know if you have any ideas.

I'm using the following package versions

```
bio2bel                   0.4.2                    pypi_0    pypi
bio2bel-kegg              0.3.0                    pypi_0    pypi
sqlalchemy                1.4.31           py38h294d835_0    conda-forge
```

**Comment by ddomingof** [comment]
I think it's the version of sqlite.
Could you downgrade it to the version from 2 years ago.
Apologies

**Comment by ddomingof** [comment]
https://pypi.org/project/SQLAlchemy/1.3.18/
This or older

**Comment by kozo2** [comment]
Thank you.
`import bio2bel_kegg` was successful with `pip install sqlalchemy==1.3.18`.
However, `kegg_manager.pupulate()` failed like #18

**Comment by kozo2** [comment]
I sent #19 .
Close this issue.
