### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by kozo2** [bio2bel/kegg#18]
`kegg_manager.populate()` failed as below.

```
(base) C:\Users\hoge>python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bio2bel_kegg
INFO: [2022-02-04 17:13:08] protmapper.resources - Could not access 'hgnc' resource file, will download.
INFO: [2022-02-04 17:13:08] protmapper.resources - Downloading 'hgnc' resource file into C:\Users\hoge\.data\protmapper\0.0.24\hgnc_entries.tsv.gz from cache.
INFO: [2022-02-04 17:13:10] protmapper.resources - Could not access 'up' resource file, will download.
INFO: [2022-02-04 17:13:10] protmapper.resources - Downloading 'up' resource file into C:\Users\hoge\.data\protmapper\0.0.24\uniprot_entries.tsv.gz from cache.
INFO: [2022-02-04 17:14:20] protmapper.resources - Could not access 'upsec' resource file, will download.
INFO: [2022-02-04 17:14:20] protmapper.resources - Downloading 'upsec' resource file into C:\Users\hoge\.data\protmapper\0.0.24\uniprot_sec_ac.txt.gz from cache.
>>> kegg_manager = bio2bel_kegg.Manager()
>>> kegg_manager.populate()
INFO: [2022-02-04 17:16:39] bio2bel.utils - downloading from source http://rest.kegg.jp/list/organism to C:\Users\hoge\.data\bio2bel\kegg\organisms.tsv
INFO: [2022-02-04 17:16:40] bio2bel.utils - downloading from source http://rest.kegg.jp/list/pathway/hsa to C:\Users\hoge\.data\bio2bel\kegg\pathways.tsv
Fetching protein information (3 threads):  29%|███████████▏                           | 99/345 [00:07<00:19, 12.81it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel\manager\abstract_manager.py", line 40, in populate_wrapped
    cls._populate_original(self, *populate_args, **populate_kwargs)
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel_kegg\manager.py", line 172, in populate
    self._populate_pathways(url=pathways_url)
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel_kegg\manager.py", line 95, in _populate_pathways
    pathways_lines = get_entities_lines(pathways_df['kegg_pathway_id'])
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel_kegg\client.py", line 55, in get_entities_lines
    return list(results)
  File "C:\Users\hoge\miniforge3\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "C:\Users\hoge\miniforge3\lib\multiprocessing\pool.py", line 868, in next
    raise value
  File "C:\Users\hoge\miniforge3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel_kegg\client.py", line 69, in ensure_kegg_entity
    urlretrieve(f'http://rest.kegg.jp/get/{entity_id}', entity_text_path)  # noqa:S310
  File "C:\Users\hoge\miniforge3\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\hoge\miniforge3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\hoge\miniforge3\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\hoge\miniforge3\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\hoge\miniforge3\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\hoge\miniforge3\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\hoge\miniforge3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
>>>
```

I'm using
```
>>> sys.version
'3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]'

```

**Comment by ddomingof** [comment]
I think KEGG blocks the API after doing X calls. Did you try to run it again after a pause?

**Comment by kozo2** [comment]
No, I didn't try to run it again after a pause.

**Comment by ddomingof** [comment]
Can you print which URL is the one causing the issue? 
Maybe we should either try: catch: error to skip it or add a blacklist for it.

**Comment by kozo2** [comment]
It looks like `http://rest.kegg.jp/link/pathway/hsa`.

**Comment by ddomingof** [comment]
Yes but its one particular pathway cause the others worked

**Comment by kozo2** [comment]
If so, I don't know how to find it.

**Comment by ddomingof** [comment]
Sorry for the delay, I just add an try catch.
https://github.com/bio2bel/kegg/commit/7ac0bf4361631375513aeb77502f8ca600b0a990

Can you clone the repo and see if it works?

**Comment by kozo2** [comment]
The fetch seems to be successful as shown below, but it fails in the next parse. I close this issue once and report it in another issue.
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bio2bel_kegg
>>> kegg_manager = bio2bel_kegg.Manager()
>>> kegg_manager.populate()
Fetching protein information (3 threads): 100%|█████████████████████████████████████| 345/345 [00:00<00:00, 428.28it/s]
loading pathways:   0%|                                                                        | 0/345 [00:00<?, ?it/s]WARNING: [2022-02-11 14:51:22] bio2bel_kegg.client - Could not split line: G00011
loading pathways:  40%|████████████████████████▏                                   | 139/345 [00:00<00:00, 1389.54it/s]WARNING: [2022-02-11 14:51:22] bio2bel_kegg.client - could not parse line: D00043  Isoflurophate
WARNING: [2022-02-11 14:51:22] bio2bel_kegg.client - could not parse line: D11651  Edotreotide gallium Ga-68
loading pathways: 100%|████████████████████████████████████████████████████████████| 345/345 [00:00<00:00, 1263.59it/s]
Fetching protein information (3 threads): 100%|████████████████████████████████████| 8113/8113 [01:43<00:00, 78.47it/s]
Parsing protein information:   0%|                                                            | 0/8113 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel\manager\abstract_manager.py", line 40, in populate_wrapped
    cls._populate_original(self, *populate_args, **populate_kwargs)
  File "c:\users\hoge\downloads\kegg-master\src\bio2bel_kegg\manager.py", line 173, in populate
    self._populate_pathway_protein(url=protein_pathway_url)
  File "c:\users\hoge\downloads\kegg-master\src\bio2bel_kegg\manager.py", line 129, in _populate_pathway_protein
    proteins = [
  File "c:\users\hoge\downloads\kegg-master\src\bio2bel_kegg\manager.py", line 130, in <listcomp>
    (entity_id, parse_protein_lines(entity_lines))
  File "c:\users\hoge\downloads\kegg-master\src\bio2bel_kegg\client.py", line 107, in parse_protein_lines
    for group, group_lines in itt.groupby(iterate_groups(lines), key=itemgetter(0)):
  File "c:\users\hoge\downloads\kegg-master\src\bio2bel_kegg\client.py", line 83, in iterate_groups
    for line in lines:
TypeError: 'NoneType' object is not iterable
>>>
```

**Comment by ddomingof** [comment]
Can you try again? I just added a new commit to try to fix it

**Comment by kozo2** [comment]
I understand. Then, I will continue to report on this issue as it is.
Even if I use https://github.com/bio2bel/kegg/commit/1bfbc82d7ab518dfef8c902dbdb3782f3a75ef62
, I still get the following error.
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bio2bel_kegg
>>> kegg_manager = bio2bel_kegg.Manager()
>>> kegg_manager.populate()
Fetching protein information (3 threads): 100%|█████████████████████████████████████| 345/345 [00:00<00:00, 441.72it/s]
loading pathways:   0%|                                                                        | 0/345 [00:00<?, ?it/s]WARNING: [2022-02-11 20:23:50] bio2bel_kegg.client - Could not split line: G00011
loading pathways:  40%|███████████████████████▊                                    | 137/345 [00:00<00:00, 1369.56it/s]WARNING: [2022-02-11 20:23:50] bio2bel_kegg.client - could not parse line: D00043  Isoflurophate
WARNING: [2022-02-11 20:23:50] bio2bel_kegg.client - could not parse line: D11651  Edotreotide gallium Ga-68
loading pathways: 100%|████████████████████████████████████████████████████████████| 345/345 [00:00<00:00, 1245.36it/s]
Fetching protein information (3 threads): 100%|████████████████████████████████████| 8113/8113 [02:21<00:00, 57.43it/s]
Parsing protein information: 100%|█████████████████████████████████████████████████| 589/589 [00:00<00:00, 8788.15it/s]
Loading proteins:   0%|                                                                        | 0/589 [00:00<?, ?it/s]WARNING: [2022-02-11 20:26:11] bio2bel_kegg.manager - no hgnc id for kegg.protein:hsa:100861540
WARNING: [2022-02-11 20:26:11] bio2bel_kegg.manager - no hgnc id for kegg.protein:hsa:3439
WARNING: [2022-02-11 20:26:11] bio2bel_kegg.manager - no hgnc id for kegg.protein:hsa:102723475
Loading proteins: 100%|███████████████████████████████████████████████████████████| 589/589 [00:00<00:00, 34656.38it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hoge\miniforge3\lib\site-packages\bio2bel\manager\abstract_manager.py", line 40, in populate_wrapped
    cls._populate_original(self, *populate_args, **populate_kwargs)
  File "c:\users\hoge\downloads\kegg-master\src\bio2bel_kegg\manager.py", line 173, in populate
    self._populate_pathway_protein(url=protein_pathway_url)
  File "c:\users\hoge\downloads\kegg-master\src\bio2bel_kegg\manager.py", line 160, in _populate_pathway_protein
    protein = kegg_protein_id_to_protein[kegg_protein_id]
KeyError: 'hsa:1544'
>>>
```

**Comment by ddomingof** [comment]
Next commit added, let's see if now...
:)

**Comment by kozo2** [comment]
Thank you. 
https://github.com/bio2bel/kegg/commit/c93f91e46e351ad0fc53c862076df04963cad34a
no longer gives an error.
```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bio2bel_kegg
>>> kegg_manager = bio2bel_kegg.Manager()
>>> kegg_manager.populate()
Fetching protein information (3 threads): 100%|████████████████████████████████████| 345/345 [00:00<00:00, 4312.50it/s]
loading pathways:   0%|                                                                        | 0/345 [00:00<?, ?it/s]WARNING: [2022-02-11 20:32:57] bio2bel_kegg.client - Could not split line: G00011
loading pathways:  40%|████████████████████████                                    | 138/345 [00:00<00:00, 1379.63it/s]WARNING: [2022-02-11 20:32:57] bio2bel_kegg.client - could not parse line: D00043  Isoflurophate
WARNING: [2022-02-11 20:32:57] bio2bel_kegg.client - could not parse line: D11651  Edotreotide gallium Ga-68
loading pathways: 100%|████████████████████████████████████████████████████████████| 345/345 [00:00<00:00, 1240.89it/s]
Fetching protein information (3 threads): 100%|████████████████████████████████████| 8113/8113 [02:59<00:00, 45.14it/s]
Parsing protein information: 100%|█████████████████████████████████████████████████| 960/960 [00:00<00:00, 8377.21it/s]
Loading proteins:   0%|                                                                        | 0/960 [00:00<?, ?it/s]WARNING: [2022-02-11 20:35:57] bio2bel_kegg.manager - no hgnc id for kegg.protein:hsa:100861540
WARNING: [2022-02-11 20:35:57] bio2bel_kegg.manager - no hgnc id for kegg.protein:hsa:3439
WARNING: [2022-02-11 20:35:57] bio2bel_kegg.manager - no hgnc id for kegg.protein:hsa:102723475
Loading proteins: 100%|███████████████████████████████████████████████████████████| 960/960 [00:00<00:00, 33102.31it/s]
>>>
```

**Comment by ddomingof** [comment]
Thanks to you for your patience and debugging!
